### ISSUE TITLE
gitbook: lab1_3_2_1_protection_mode 关于段属性粒度位

### ISSUE THREAD

**Issue by misakar** [chyyuu/ucore_os_lab#16]
https://objectkuan.gitbooks.io/ucore-docs/content/lab1/lab1_3_2_1_protection_mode.html
这一章说到: 
![2016-11-12 5 11 01](https://cloud.githubusercontent.com/assets/10671733/20236784/045d4d60-a8fb-11e6-97bd-315c428ae3a8.png)
如果是4k字节为单位, 所表示的范围应该是4G吧.

谢了!

**Comment by neo1218** [comment]
![2016-11-12 5 14 41](https://cloud.githubusercontent.com/assets/10671733/20236796/863abac0-a8fb-11e6-9e6d-7b842db1665b.png)
呃，应该是下面的

**Comment by objectkuan** [comment]
Sorry for the delay.
A fixed version will be found [here](https://chyyuu.gitbooks.io/ucore_os_docs/content/lab1/lab1_3_2_1_protection_mode.html).

The link (https://objectkuan.gitbooks.io/ucore-docs/content/lab1/lab1_3_2_1_protection_mode.html) is no longer under maintenance.

**Comment by chyyuu** [comment]
Thank you!
