### ISSUE TITLE
关于macos上执行lab1的make命令

### ISSUE THREAD

**Issue by Mod233** [chyyuu/ucore_os_lab#19]
您好，我参考readme中讲述的，
brew install i386-elf-gdb
brew install i386-elf-gcc
每个大概都花了一小时左右，但是当我再执行make的时候，同样遇到了一下提示：

/bin/sh: i386-elf-gcc: command not found
make: *** Deleting file `obj/boot/bootmain.d'
xxxxx

应该是i386-elf-gcc的问题，是我brew install 失败了 还是应该加一个 alias这样的别名或者ln -s 这样的命令？ 刚学习这门课程，实在有点搞不懂这里，希望能指导一下，谢谢了

**Comment by Mod233** [comment]
我重复安装很多次，但之后总是出现：
Homebrew brew install i386-elf-gcc
Updating Homebrew...
==> Installing i386-elf-gcc from altkatz/gcc_cross_compilers
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2
Already downloaded: /Users/sperc4/Library/Caches/Homebrew/i386-elf-gcc-4.9.3.tar.bz2
Error: SHA256 mismatch
Expected: 1934f3f68fe477299fe929e527c62d800f8b1b01ca74cc218f90459715ace296
Actual: 2332b2a5a321b57508b9031354a8503af6fdfb868b8c1748d33028d100a8b67e
Archive: /Users/sperc4/Library/Caches/Homebrew/i386-elf-gcc-4.9.3.tar.bz2
To retry an incomplete download, remove the file above.
。。。不解

**Comment by Elliot-Chan** [comment]
SHA256 不匹配，是不是网络问题导致软件包只下载了一部分，试试删除i386-elf-gcc-4.9.3.tar.bz2这个文件重新安装试试。如果不行的话，我不知道brew有没有　--forch　选项，如果有的话，禁用校验强制安装试试？实在不行，手工编译安装。
我只提供如何安装那个软件包的想法，勿回

**Comment by Phantom-Fan** [comment]
@Mod233 Hi, I managed to fix this SHA256 mismatch error by forking the original repo and changed the sha256 expected value to by pass this check. I hope this method could solve your problem.

**Comment by Mod233** [comment]
@Phantom-Fan thank u for your help. but i don't kown what means "changed the sha256 expected value to by pass this check" , could u please give some more details on how to avoid checking the  SHA256...  ^_^

**Comment by Phantom-Fan** [comment]
@Mod233 You are welcome to check my github repo. There is one I forked from the original author. You could do `brew untap altkatz/homebrew-gcc_cross_compilers` and then 'brew tap Phantom-Fan/homebrew-gcc_cross_compilers.git'.

**Comment by Mod233** [comment]
@Phantom-Fan thanks for your generous help. after i did what you said, i succeed install the gcc-i386 , and make the project. what's more i also learn some commands about "brew".

**Comment by noname007** [comment]
why not send a pr......
