### ISSUE TITLE
关于kern/init/init.c里面memset的一个问题

### ISSUE THREAD

**Issue by rod-lin** [chyyuu/ucore_os_lab#24]
您好，我在init.c里面看到这一行代码

    memset(edata, 0, end - edata);

我个人理解是初始化全局变量用的。不知道对不对。。

但是我感觉这样初始化全局变量会导致default_pmm.c里面设置的manager的函数指针被清空导致pmm_init继续不下去(>=lab2)？
我在我机器上(ubuntu 17.04 64位)试的时候就会这个问题。
不知道是不是我哪里看错了或者编译参数没有设置对所以想请教一下。。

谢谢！

**Comment by objectkuan** [comment]
IIUC, `default_pmm_manager` lives in the .rodata section instead of the .data section.
You might check for this by using `objdump` to disassemble `kern/mm/default_pmm.o`.

**Comment by rod-lin** [comment]
Oh, I found `default_pmm_manager` in `.data.rel.ro`,
and it seems like it's between the begin and end addresses of .bss section declared in `tools/kernel.ld`.

No idea why... (maybe the function pointers in `default_pmm_manager` need relocations?)
Is this `.data.rel.ro` a gcc-only thing?

Thanks

**Comment by objectkuan** [comment]
Hmm interesting.. Not sure why this happens. It might has something to do with your toolchain.
You could append `-v` to `CFLAGS` in `Makefile`, and `make clean && make -n > build.log 2>&1`. All commands and compiler options (including the built-in opts) should be found in `build.log`. And we might be able to get some clues from it.

**Comment by rod-lin** [comment]
I got this output:

    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.3.0-12ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 
    COLLECT_GCC_OPTIONS='-I' 'boot/' '-v' '-fno-builtin' '-Wall' '-ggdb' '-m32' '-gstabs' '-nostdinc' '-fno-stack-protector' '-I' 'libs/' '-Os' '-nostdinc' '-MM' '-MT' 'obj/boot/bootmain.o obj/boot/bootmain.d' '-mtune=generic' '-march=i686'
     /usr/lib/gcc/x86_64-linux-gnu/6/cc1 -E -quiet -nostdinc -nostdinc -v -I boot/ -I libs/ -imultilib 32 -imultiarch i386-linux-gnu -MM -MT obj/boot/bootmain.o obj/boot/bootmain.d boot/bootmain.c -m32 -mtune=generic -march=i686 -Wall -fno-builtin -fno-stack-protector -ggdb -gstabs -fworking-directory -Os -Wformat-security
    #include "..." search starts here:
    #include <...> search starts here:
     boot/
     libs/
    End of search list.
    COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/
    LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/../../../i386-linux-gnu/:/lib/i386-linux-gnu/:/usr/lib/i386-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../i386-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../:/lib/i386-linux-gnu/:/lib/:/usr/lib/i386-linux-gnu/:/usr/lib/
    COLLECT_GCC_OPTIONS='-I' 'boot/' '-v' '-fno-builtin' '-Wall' '-ggdb' '-m32' '-gstabs' '-nostdinc' '-fno-stack-protector' '-I' 'libs/' '-Os' '-nostdinc' '-MM' '-MT' 'obj/boot/bootmain.o obj/boot/bootmain.d' '-mtune=generic' '-march=i686'



The compiler flags are

    gcc -Ikern/init/ -v -fno-builtin -Wall -ggdb -m32 -gstabs -nostdinc  -fno-stack-protector -Ilibs/ -Ikern/debug/ -Ikern/driver/ -Ikern/trap/ -Ikern/mm/ -Ikern/libs/ -Ikern/sync/ -Ikern/fs/ -Ikern/process/ -Ikern/schedule/ -Ikern/syscall/ -Ikern/fs/swap/ -Ikern/fs/vfs/ -Ikern/fs/devs/ -Ikern/fs/sfs/ -c kern/init/init.c -o obj/kern/init/init.o


And the ld flags are

    ld -m    elf_i386 -nostdlib -T tools/kernel.ld -o bin/kernel  [all the object files]

**Comment by objectkuan** [comment]
Hi Rod, I finally find a solution that may work. I notice that the gcc was compiled with `--enable-default-pie`. I built a gcc-6 with this version and reproduce your issue locally.

The solution that works for me is to append a cflag to disable pie by adding a line in the Makefile:
`CFLAGS  += -fno-pie`

Could you try and see if it works?

**Comment by rod-lin** [comment]
It works!!! All the `.data.rel*` sections were gone.
Thank you!!!
