### ISSUE TITLE
brew install i386-elf-gcc conflicting version recursive dependencies

### ISSUE THREAD

**Issue by 9394974** [chyyuu/ucore_os_lab#25]
after add brew tap，I get some error and don't know how to fix:
`
➜  lab1 git:(master) ✗ brew tap altkatz/homebrew-gcc_cross_compilers
Updating Homebrew...
==> Tapping altkatz/gcc_cross_compilers
Cloning into '/usr/local/Homebrew/Library/Taps/altkatz/homebrew-gcc_cross_compilers'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 10), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (17/17), done.
Checking connectivity... done.
Tapped 15 formulae (53 files, 43.8KB)
➜  lab1 git:(master) ✗ brew install i386-elf-gcc
==> Installing i386-elf-gcc from altkatz/gcc_cross_compilers
Error: altkatz/gcc_cross_compilers/i386-elf-gcc contains conflicting version recursive dependencies:
  gmp, gmp@4, mpfr, mpfr@2, libmpc, libmpc@0.8
View these with 'brew deps --tree altkatz/gcc_cross_compilers/i386-elf-gcc'.

`

May be the tap need to fix ?

**Comment by CFM880** [comment]
> brew untap altkatz/homebrew-gcc_cross_compilers
brew tap nativeos/i386-elf-toolchain
brew install i386-elf-binutils i386-elf-gcc i386-elf-gdb

换一个仓库，编译能过，没有冲突

**Comment by chyyuu** [comment]
我没用过mac。搞定就好！
