### ISSUE TITLE
Is the comments in _fifo_swap_out_victim accurate？

### ISSUE THREAD

**Issue by markjenny** [chyyuu/ucore_os_lab#26]
```
static int
_fifo_swap_out_victim(struct mm_struct *mm, struct Page ** ptr_page, int in_tick)
{
     list_entry_t *head=(list_entry_t*) mm->sm_priv;
         assert(head != NULL);
     assert(in_tick==0);
     /* Select the victim */
     /*LAB3 EXERCISE 2: YOUR CODE*/ 
     //(1)  unlink the  earliest arrival page in front of pra_list_head qeueue
     //(2)  set the addr of addr of this page to ptr_page
     return 0;
}
```
the code above is in /labcodes/lab3/kern/mm/swap_fifo.c. It is puzzle to me for the comments `set the addr of addr of this page to ptr_page`. The comment is a little misleading, I think. 
We should change the value of *ptr_page instead of the ptr_page. So I think the comment `set the addr of  addr of this page to ptr_page` should be changed to `set the addr of this page to *ptr_page`.

what is your opinion about this?

**Comment by chyyuu** [comment]
Thank you!
I update the comments according to your advice.
