### ISSUE TITLE
bootloader.out of Lab1_answer failed to be signed. 

### ISSUE THREAD

**Issue by LiSTlst** [chyyuu/ucore_os_lab#27]
`+ ld bin/bootblock
ld -m    elf_i386 -nostdlib -N -e start -Ttext 0x7C00 obj/boot/bootasm.o obj/boot/bootmain.o -o obj/bootblock.o
'obj/bootblock.out' size: 620 bytes
620 >> 510!!
Makefile:152: recipe for target 'bin/bootblock' failed
make: *** [bin/bootblock] Error 255
`
The size of bootloader.out is larger than 510B.

**Comment by twd2** [comment]
Please provide the version of your GCC or another compiler.

**Comment by chyyuu** [comment]
这是编译器版本的一个问题。
如果gcc 6+，可能会出现这种问题。但用gcc-4, gcc-5 应该没有问题。
