### ISSUE TITLE
Lab1中，启动os时，在lgdt函数中无法继续执行

### ISSUE THREAD

**Issue by ylink-lfs** [chyyuu/ucore_os_lab#51]
lab1中使用make debug命令调试os时，执行至/labcodes/lab1/kern/mm/pmm.c的lgdt函数的第62行，反汇编代码mov gs, eax处，当前CS值为0x8，EIP为0x102C67。使用stepi执行下一条指令后，CS、EIP的值分别变为0xF000、0xE05B（跳转到了刚启动的状态），无法继续执行lgdt函数。gcc版本为7.3.0、ubuntu版本为Ubuntu 18.04.2 LTS。

**Comment by twd2** [comment]
ref: #22
