### ISSUE TITLE
关于qemu默认内存的问题

### ISSUE THREAD

**Issue by WorstIrelia** [chyyuu/ucore_os_lab#56]
看到makefile qemu的命令并没有设定内存的大小，也就是128MB。尝试加大内存的时候会导致page的数量变大，溢出最开始的4MB地址。还有一个问题是LAB2中将0x00000000 - 0x38000000映射到了0xC0000000 - 0xF8000000, 但是物理内存只有128MB。尝试访问了一下映射中不合理的内存区域，没有报错，但是无论怎么改不合理的内存区域中的值，结果都是0。这样直接映射是合理的吗？

**Comment by moonfisher** [comment]
这个地方我也觉得有问题，我的做法是直接修改 entry.S 里的映射，直接把 0xC0000000 ~ 0xF8000000 地址空间一次全部映射好，这样 qemu 即使模拟 1024M 的内存，也能正常运行
