### ISSUE TITLE
执行make grade 报错

### ISSUE THREAD

**Issue by xiekc** [chyyuu/ucore_os_lab#62]
执行make grade，出现
: not found.sh: 2: tools/grade.sh: 
tools/grade.sh: 157: tools/grade.sh: Syntax error: ")" unexpected (expecting "then")
make: *** [grade] Error 2
等报错

**Comment by xiekc** [comment]
重新下载后就好了。

**Comment by pleasenott** [comment]
您好，我也遇见这个问题了，而且重新下载后也解决不了，请问您的具体下载指的是什么呢
