### ISSUE TITLE
这个用的什么汇编语言啊

### ISSUE THREAD

**Issue by guoxiang666** [chyyuu/ucore_os_lab#68]
陈渝老师您好 ，为了这个项目 我花了一年学c/c++和操作系统原理，对汇编不太懂，请问这个项目用的是什么汇编?
arm的还是x86的呢？ 如果是x86则是intel的还是at&t的？我现在刚学完8086的，对这些不太懂， 我想知道接下来怎么学

**Comment by rhanqtl** [comment]
x86 汇编，AT&T 格式，汇编的部分并不多，而且感觉基本上用的是比较常见的汇编指令，学过 8086 应该够了

**Comment by moveaxebx** [comment]
> x86 汇编，AT&T 格式，汇编的部分并不多，而且感觉基本上用的是比较常见的汇编指令，学过 8086 应该够了

感谢你的回复 我刚看完王爽老师的汇编语言 ，学的都是实模式下8086的东西 接下来怎么看与偶什么推荐的吗 ia32的我都没太学过包括保护模式那些

**Comment by homer12** [comment]
保護模式就看看Intel手冊第三卷開頭幾章就夠了，其實6.828這門課的資料裏面也有說。
匯編如果你已經會了Intel語法的話，AT&T其實就是換個格式問題不大。
