### ISSUE TITLE
Make grade fails with error 1

### ISSUE THREAD

**Issue by SaoYan** [chyyuu/ucore_os_lab#72]
I've tried running ```make grade``` for lab 1 - lab 3 (**the lab codes_answers, not my own code**), and they all fails with Error 1.

Platform: macOs Catalina

- lab1_result
```
Check Output:            (1.0s)
  -check ring 0:                             no $qemu_out
  -check switch to ring 3:                   no $qemu_out
  -check switch to ring 0:                   no $qemu_out
  -check ticks:                              no $qemu_out
Total Score: 0/40
make: *** [grade] Error 1
```

- lab2_result
```
Check PMM:               (1.0s)
  -check pmm:                                no $qemu_out
  -check page table:                         no $qemu_out
  -check ticks:                              no $qemu_out
Total Score: 0/50
make: *** [grade] Error 1
```

- lab3_result
```
Check SWAP:              (1.0s)
  -check pmm:                                no $qemu_out
  -check page table:                         no $qemu_out
  -check vmm:                                no $qemu_out
  -check swap page fault:                    no $qemu_out
  -check ticks:                              no $qemu_out
Total Score: 0/45
make: *** [grade] Error 1
```

**Comment by AGRonin** [comment]
您好，请问问题是否得到了解决？我在M2芯片 MacOS Tahoe上运行VMWare Fusion虚拟机Ubuntu 20.04 时遇到了相同的问题，其答案判分为0，显示no $qemu_out并且报错Error 1。感谢您的回复，已经六年过去了即使您已经忘记了……
Hello sir, may I ask if the issue has been resolved? I encountered the same problem when running a VMware Fusion virtual machine with Ubuntu 20.04 on an M2 chip MacBook with MacOS Tahoe. The answer was scored as 0, showing “no $qemu_out” and reporting “Error 1.” Thank you for your reply even if you may have forgotten the project…
