### ISSUE TITLE
lab5_answer和lab6等“!PageReserved(p) && !PageProperty(p)”错误及其原因

### ISSUE THREAD

**Issue by zhuyixiaoxiannv** [chyyuu/ucore_os_lab#85]
我直接运行lab5_answer（没有改动任何代码）都会报这个错误——然而这个错误在lab6里面也产生了（之后的lab我还没有做，应该也有这个问题）。
我经过检查之后，发现确实是源代码的一个bug导致的。因此在这里将其说明原因及解决方案（但我不确定是否有人发现并解决了他，至少master和几个pull request我粗略看了，好像并没有）。
在pmm.c中的check_boot_pgdir()函数中，虽然最后将pgdir[0]等等做了清理，但是在系统的快表TLB中依然存在着0x100这个地址对应的页表。而不巧的是，在vmm.c中，check_pgfault()函数中也用到了这个0x100地址，所以在这段代码运行的时候，因为关于这个地址的快表没有被清理掉，从而导致没有发生页中断，缺少了一些处理，从而在free page的时候，报这个错误——这个错误确实存在，但并不一定产生，因为快表的替换机制问题，很有可能跑到vmm.c这行代码的时候，这页快表已经被替换掉了。
解决方案就是在check_boot_pgdir()函数的末尾加上两行。
tlb_invalidate(boot_pgdir, 0x100);
tlb_invalidate(boot_pgdir, 0x100+PGSIZE);
另外，这里面check的地方很多，我不确定其他地方是否会由于TLB的问题导致同样的错误。
如果有什么问题，请联系3150101706@zju.edu.cn

**Comment by chyyuu** [comment]
Thank you very much!
